Add Python3 Support.
This is required or the install will error with: 
  File "/usr/local/lib/python3.4/dist-packages/FinexAPI/FinexAPI.py", line 20
    print "Your pub: " + str(API_KEY)
                     ^
SyntaxError: invalid syntax